name:                ray-tracing
version:             0.1.0.0
github:              "shaunplee/ray-tracing"
license:             BSD3
author:              "Shaun Lee"
maintainer:          "shaun@curlyfri.es"
copyright:           "Copyright (c) 2020 Shaun Lee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shaunplee/ray-tracing#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - mtl
    - mersenne-random-pure64

executables:
  ray-tracing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-tracing

tests:
  ray-tracing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ray-tracing
